// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: del_follow.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const delFollow = `-- name: DelFollow :exec
DELETE FROM feed_follows
WHERE user_id = $1 AND feed_id = $2
`

type DelFollowParams struct {
	UserID uuid.UUID
	FeedID uuid.UUID
}

func (q *Queries) DelFollow(ctx context.Context, arg DelFollowParams) error {
	_, err := q.db.ExecContext(ctx, delFollow, arg.UserID, arg.FeedID)
	return err
}
